name: firmware

on:
    push:
        branches: [main]
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - uses: dtolnay/rust-toolchain@stable
              with:
                targets: thumbv7em-none-eabihf
                components: rustfmt, clippy

            - uses: Swatinem/rust-cache@v2

            - name: Format
              run: cargo fmt --check

            - name: Clippy
              run: cargo clippy --release -- -D warnings

            - name: Build
              run: cargo build --release

            - uses: actions/upload-artifact@v7
              with:
                name: firmware-elf
                path: target/thumbv7em-none-eabihf/release/embedded-rust